export enum QueryKind {
  RENIEC_LOOKUP = "reniec_lookup",
  INCIDENCIA_REGISTER = "incidencia_register",
  VALIDATE_USER = "validate_user",
  VERIFY_CODE = "verify_code",
  ANALYZE_MAIN_MENU_INTENT = "analyze_main_menu_intent",
  RESOLVE_DISTRITO_AI = "resolve_distrito_ai",
  RESOLVE_FECHA_AI = "resolve_fecha_ai",
  EXTRACT_SELECTION_HINTS = "extract_selection_hints",
  SEARCH_UBIGEO = "search_ubigeo",
  LIST_ESPECIALIDADES = "list_especialidades",
  LIST_ESTABLECIMIENTOS = "list_establecimientos",
  LIST_FECHAS = "list_fechas",
  LIST_HORAS = "list_horas",
  BOOK_APPOINTMENT = "book_appointment",
  LIST_REFERENCES = "list_references",
  ANALYZE_INCIDENCIA_FOTO_INTENT = "analyze_incidencia_foto_intent",
}
