export const LOG_EVENTS = [
  "turn.start",
  "turn.note",
  "turn.external",
  "turn.end",
  "turn.failed",
  "turn.lock_timeout",
  "turn_lock.waited",
  "external.http",
  "minsa.book_appointment.failed",
  "minsa.catalog.rows_discarded",
  "minsa.request_blocked",
  "ai.fallback",
  "ai.provider_unknown",
  "perimeter.dropped",
  "perimeter.rejected",
  "perimeter.muted",
  "perimeter.banned",
  "inbound.expired_on_boot",
  "inbound.expire_failed",
  "webhook.message_failed",
  "webhook.entry_failed",
  "webhook.fixed_reply_failed",
  "whatsapp.send_failed",
  "whatsapp.typing_failed",
  "whatsapp.media_failed",
  "incidencia.invalid_submission",
  "incidencia.not_persisted",
  "incidencia.media_not_stored",
  "incidencia.media_upload_failed",
  "incidencia.persist_failed",
  "incidencia.establecimiento_lookup_failed",
  "incidencia.daily_limit_reached",
  "sandbox.cors_invalid_origin",
  "config.invalid",
] as const;

export type LogEvent = (typeof LOG_EVENTS)[number];

export const TURN_NOTE_KINDS = [
  "shortcut",
  "lexical_guard",
  "session_expired",
  "confirmation_unknown",
  "menu_fallback",
  "no_coverage",
  "booking_retry",
  "booking_rejected",
  "first_contact",
  "out_of_scope",
  "hora_declined",
  "cita_closed",
  "exit_intent",
  "change_distrito",
] as const;

export type TurnNoteKind = (typeof TURN_NOTE_KINDS)[number];
